"""Generate the XPPAUT implementation of the reduced single-segment model.

The generated ODE file is intentionally explicit: each chemical and electrical
input is expanded from the first 17 rows and columns of the project
connectivity matrices.  This keeps XPPAUT/AUTO's Jacobian transparent while
making ``src/segment.py`` the source of truth for topology and parameters.
"""

from pathlib import Path
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import segment  # noqa: E402
import settings  # noqa: E402


OUTPUT = Path(__file__).with_name("single_segment.ode")


def _number(value):
    """Return a compact, deterministic XPPAUT numeric literal."""
    return f"{float(value):.12g}"


def _weighted_sum(row, signal):
    terms = []
    for index, weight in enumerate(row):
        if weight == 0:
            continue
        name = f"{signal}{index}"
        terms.append(name if weight == 1 else f"{_number(weight)}*{name}")
    return "+".join(terms) if terms else "0"


def _gap_sum(row, post):
    terms = []
    for pre, weight in enumerate(row):
        if weight == 0:
            continue
        difference = f"(v{post}-v{pre})"
        terms.append(difference if weight == 1 else f"{_number(weight)}*{difference}")
    return "+".join(terms) if terms else "0"


def _drive(index):
    cell_class = int(segment.CLASSES[index])
    terms = []
    if cell_class in segment.AVA_CLASSES:
        terms.append("iava")
    if cell_class in segment.AVB_CLASSES:
        terms.append("iavb")
    return "+".join(terms) if terms else "0"


def build_ode():
    """Return the complete XPPAUT ``.ode`` source as text."""
    settings.reset_defaults()
    segment.configure()

    lines = [
        "# C. elegans single segment: reduced (V,w) system for XPPAUT/AUTO",
        "# Generated by xppaut/generate_single_segment.py; do not edit by hand.",
        "# Cells: 0-1 AS, 2 DA, 3 DB, 4 DD, 5-6 VD, 7-8 VB, 9-10 VA,",
        "#        11-13 dorsal muscle, 14-16 ventral muscle.",
        "# Connectivity convention is row=post, column=pre.",
        "",
        "# AUTO-facing command parameters come first.",
        "par iava=0,iavb=0",
        (
            f"par gse={_number(settings.G_syne)},"
            f"gsi={_number(settings.G_syni)},ggap={_number(settings.G_gap)}"
        ),
        (
            f"par ksyn={_number(settings.k_syn)},"
            f"beta={_number(settings.beta)},tauw={_number(settings.tau_w)}"
        ),
        (
            f"par cap={_number(settings.C)},gmem={_number(settings.g)},"
            f"ere={_number(settings.E_syne)},eri={_number(settings.E_syni)}"
        ),
        (
            f"par vl={_number(settings.L)},vt={_number(settings.T)},"
            f"vh={_number(settings.H)},vth={_number(settings.V_th)}"
        ),
        (
            f"par m1={_number(settings.m1)},m2={_number(settings.m2)},"
            f"m3={_number(settings.m3)},m4={_number(settings.m4)}"
        ),
        "",
        "# Piecewise Yuval membrane current, recovery target, and synaptic gate.",
        (
            "memb(v)=if(v>vh)then(m4*(-v+vh))else("
            "if(v>=vt)then(m3*(v-vh)*(v-vt))else("
            "if(v>=vl)then(m2*(v-vl)*(v-vt))else(m1*(-v+vl))))"
        ),
        "winf(v)=if(v>vt)then(beta*(v-vt))else(0)",
        "gate(v)=1/(1+exp(-ksyn*(v-vth)))",
        "",
        "# Presynaptic activation. Fixed variables are evaluated in file order.",
    ]

    lines.extend(f"s{i}=gate(v{i})" for i in range(segment.N_CELLS))
    lines.extend(["", "# Expanded chemical and gap-junction inputs by postsynaptic cell."])
    for post in range(segment.N_CELLS):
        lines.append(f"e{post}={_weighted_sum(segment.E_CONN[post], 's')}")
        lines.append(f"i{post}={_weighted_sum(segment.I_CONN[post], 's')}")
        lines.append(f"j{post}={_gap_sum(segment.GJ_CONN[post], post)}")

    lines.extend(["", "# Voltage and recovery equations (34 dynamical variables)."])
    for post in range(segment.N_CELLS):
        voltage_rhs = (
            f"(gmem*memb(v{post})-w{post}"
            f"-gse*e{post}*(v{post}-ere)-gsi*i{post}*(v{post}-eri)"
            f"-ggap*j{post}+{_drive(post)})/cap"
        )
        lines.append(f"v{post}'={voltage_rhs}")
        lines.append(f"w{post}'=(winf(v{post})-w{post})/tauw")

    lines.extend(
        [
            "",
            "# Rest initial condition.",
            "init v0=-70,v1=-70,v2=-70,v3=-70,v4=-70,v5=-70",
            "init v6=-70,v7=-70,v8=-70,v9=-70,v10=-70,v11=-70",
            "init v12=-70,v13=-70,v14=-70,v15=-70,v16=-70",
            "init w0=0,w1=0,w2=0,w3=0,w4=0,w5=0,w6=0,w7=0,w8=0",
            "init w9=0,w10=0,w11=0,w12=0,w13=0,w14=0,w15=0,w16=0",
            "",
            "# Useful readouts: mean command targets and mean muscle voltages.",
            "aux avam=(v0+v1+v2+v9+v10)/5",
            "aux avbm=(v0+v1+v3+v7+v8)/5",
            "aux dorsm=(v11+v12+v13)/3",
            "aux ventm=(v14+v15+v16)/3",
            "",
            "# Stiff time integration and practical AUTO defaults.",
            "@ meth=cvode,dt=1,total=20000,nout=10,tol=1e-8,atol=1e-8",
            "@ maxstor=200000,bound=100000,bell=0",
            "@ autovar=v4,parmin=0,parmax=6,autoxmin=0,autoxmax=6",
            "@ autoymin=-80,autoymax=-20,ds=0.01,dsmax=0.05,nmax=10000,npr=20",
            "done",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    OUTPUT.write_text(build_ode())
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
